apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "probe-endpoint.fullname" . }}
  labels:
    app: {{ template "probe-endpoint.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "probe-endpoint.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        {{- if .Values.iperf.enabled }}
        - name: probe-endpoint-iperf
          image: travelping/nettools
          ports:
            - containerPort: {{ .Values.iperf.iperfport }}
              name: iperf
          command: ["/bin/sh"]
          args:
            - -c
            - |
              iperf3 {{ .Values.iperf.mode }} {{ .Values.iperf.options }}
        {{- end }}

        {{- if .Values.http.enabled }}
        - name: probe-endpoint-http
          image: ubuntu
          command: ["/bin/bash"]
          args:
            - -c
            - |
              apt-get update && apt-get install curl -y
              curl -L https://github.com/mgumz/knut/releases/download/v1.0.1/knut.linux.x64.amd64 --output knut
              chmod 755 knut
              ./knut -bind=":{{ .Values.http.httpPort }}" {{ .Values.http.options }}
          ports:
            - containerPort: {{ .Values.http.httpPort }}
              name: http
        {{- end }}

        {{- if .Values.speedtest.enabled }}
        - name: probe-endpoint-speedtest
          image: tianon/speedtest
          ports:
            - containerPort: {{ .Values.speedtest.port }}
              name: speedtest-port
        {{- end }}


    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
